### ISSUE TITLE
Shortcut in windows not working

### ISSUE THREAD

**Issue by zanozik** [pschweitz/insidelog#3]
Is there a way to run the program like you instruct us in README and PDF, instead of launching ugly .bat file, cluttering desktop. I guess this has something to do with .bat file having `ALL RESTRICTED APPLICATION PACKAGES` permission principal...

**Comment by zanozik** [comment]
NVM, looks like a virus.
Doesn't work on remote OR local files.
Take 40% CPU of my i5-6400 even if NO log is running.
Author reported.

**Comment by recordins** [comment]
Hi I just tested by creating a shortcut on windows 10.
No problem, you can then change the icon.

I want to thank you for your your second message, as it is typically a troll message, denigrating without giving any information.

It is a good sign, if not the best, that relates a growing popularity :1st_place_medal:

Consider changing your hardware and moving to Linux if you are facing such problems :+1: .
Cheers,
